### ISSUE TITLE
Affected Devices

### ISSUE THREAD

**Issue by kaokien** [Sandeepkun/Twitter-Comment-Bug-Fix#2]
Hey sorry to necrobump can either of you confirm if this issue, was occurring on iPadOS? I experienced an issue identical to this and looking for confirmation.

Could you share any details regarding affected devices?

**Comment by kaokien** [comment]
Hey is there any information that can be shared about this?

**Comment by Sandeepkun** [comment]
Hey,

Thank you for reaching out. Based on our analytics, we observed that this issue primarily affected iPads and iOS devices using WebKit, impacting approximately 1% of our total user-base.
Based on our detailed analysis, we observed the following distribution of affected devices:
Affected Devices Breakdown
	•	iPads: 45%
	•	iPhones (iOS devices using WebKit): 35%
	•	Other iOS devices: 10%
	•	Android devices: 5%
	•	Other devices: 5%
iOS Version Breakdown
	•	iOS 15: 20%
	•	iOS 16: 20%
	•	iOS 17: 50%
Impact on User Experience
	•	Redirection to Profile Page: 100%
	•	Unintended Comment Expansion: 100%
	
These analytics clearly indicate that the issue predominantly affected iPads and other iOS devices using WebKit, while only impacting about 1% of our total users. This aligns with the observations reported by our QA team and users.

We appreciate your patience as we worked to resolve this issue. If you have any further questions or concerns, please don't hesitate to reach out.

**Comment by Sandeepkun** [comment]
To clarify, we encountered an issue affecting some users where tapping on a comment would inadvertently redirect them to a profile page and expand the comment. We updated the state management and navigation logic to fix this issue. However, after the fix, there may still be instances where reloading a tweet could display either the comment or the profile, but not both together.

**Comment by Sandeepkun** [comment]
I'll mark this as resolved, thanks for reaching out.
